name: Rumble

on:
    push:
      branches: [ master ]

jobs:
    deploy-docker:
      runs-on: ubuntu-latest
  
      steps:

      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Build, tag, and push image to Amazon ECR
        env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ steps.login-ecr.outputs.registry }}/thecat/rumble
            IMAGE_TAG: ${{ github.sha }}
        run: |
          docker pull $ECR_REPOSITORY:latest
          docker build -f rumble/docker/Dockerfile -t $ECR_REPOSITORY --build-arg GIT_TAG=$IMAGE_TAG --cache-from $ECR_REPOSITORY:latest .
          docker tag $ECR_REPOSITORY $ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REPOSITORY
          docker push $ECR_REPOSITORY:$IMAGE_TAG
  
      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}

      - name: Rumble
        run: "for i in rumble/docker/entrants/*; do aws lambda invoke --function-name rumble --payload '{\"entrants\": [\"'${i##*/}'\"], \"group\": \"smoke\", \"tag\": \"'${{ github.sha }}'\"}' log; done;"

    deploy-web:
      runs-on: ubuntu-latest
    
      steps:

      - uses: actions/checkout@v2

      - name: Use Node.js Latest
        uses: actions/setup-node@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2

      - name: Build website
        working-directory: ./rumble/web
        run: |
          yarn install
          npm run export

      - name: Deploy static site to S3 bucket
        run: aws s3 sync rumble/web/out s3://www.rumbletoon.com/
